### PR TITLE
feature: radio::component Blade component

### PR DESCRIPTION
**Pull request by ryangjchandler**
This pull request introduces a new `<x-radio::component>` Blade component that can tidy up your markup a little bit.

Here's how you would use it:

```blade
<x-radio::component :is="$component">
    <p x-text="name"></p>
</x-radio::component>
```

You can also pass through attributes. These will be sent to the `__invoke` method on your component class, just like `@radio($component, ['name' => 'Ryan'])` would.

```blade
<x-radio::component :is="\App\Http\Components\Example::class" name="Ryan">
    <input type="text" x-model="name">
</x-radio::component>
```

### CODE REVIEW

**Comment by iksaku** [comment]
Why not follow a path similar to Livewire for this syntax?

Something like `<radio:my-component />`

**Comment by ryangjchandler** [comment]
@iksaku There's added complexity with that approach. You need to extend the compiler & handle the RegEx, with the Blade component approach we let Laravel do the heavy lifting instead.

**Comment by iksaku** [comment]
Fair enough.

Wouldn't it be ok to also give the ability to merge custom `x-data` attribute when there's no need to keep track of some states in the backend?

For things like open/close toggles for example. [Here's an example of that possibility](https://github.com/iksaku/FIMEats/blob/c374c64094b427d59d50753988ff9e35aafff8ad/resources/views/components/rate-modal.blade.php) (which actually works)

**Comment by danharrin** [comment]
> Fair enough.
> 
> Wouldn't it be ok to also give the ability to merge custom `x-data` attribute when there's no need to keep track of some states in the backend?
> 
> For things like open/close toggles for example. [Here's an example of that possibility](https://github.com/iksaku/FIMEats/blob/c374c64094b427d59d50753988ff9e35aafff8ad/resources/views/components/rate-modal.blade.php) (which actually works)

I really like this idea 👍

**Comment by ryangjchandler** [comment]
> Fair enough.
> 
> 
> 
> Wouldn't it be ok to also give the ability to merge custom `x-data` attribute when there's no need to keep track of some states in the backend?
> 
> 
> 
> For things like open/close toggles for example. [Here's an example of that possibility](https://github.com/iksaku/FIMEats/blob/c374c64094b427d59d50753988ff9e35aafff8ad/resources/views/components/rate-modal.blade.php) (which actually works)

Yeah, this concept of mixins is something I wrote about quite a while ago on my blog. 

I imagine this would be relatively simple to do.

**Pull request closed without merging**
